In [9]:
import numpy as np

# 1D array:
array = np.array([1,2,3,4,5])
print(type(array))
array

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [11]:
# 2D array:
array = np.array([[1,2,3,4],[5,6,7,8]]) 
print(type(array))
print(array)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Creating a 2D NumPy array filled with zeros (3 rows × 4 columns)

np.zeros ((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Creating a 2D NumPy array filled with ones (3 rows × 4 columns)

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# Create a 2×3 NumPy array where all elements are filled with 4

np.full((2,3), 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [17]:
# Indentity Matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# Create an array starting from 0 up to 100 (excluding 100) with a step of 10

np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Evenly Speced aray

np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [ ]:
import numpy as np

# Create a 3×5 NumPy matrix with random integers between 37 and 99
matrix = np.random.randint(37, 100, size=(3, 5))

# Print the matrix
print(f"Matrix: \n{matrix}")


print(f"the shape of the matrix: {matrix.shape}")   # Print the shape of the matrix (rows, columns)
print(f"the total number of elements: {matrix.size}")    # Print the total number of elements in the matrix
print(f"the total number of elements: {matrix.ndim}")    # Print the number of dimensions of the matrix


Matrix: 
[[90 46 47 49 83]
 [64 56 46 56 46]
 [93 39 49 69 61]]
(3, 5)
15
2


In [34]:
# Reshape the matrix from 3×5 to 5×3 (total elements remain the same)

reshapeMatrix = matrix.reshape((5,3))
print(reshapeMatrix)

[[90 46 47]
 [49 83 64]
 [56 46 56]
 [46 93 39]
 [49 69 61]]


In [38]:
# Convert 2D array to 1D array

print(matrix.flatten())

[90 46 47 49 83 64 56 46 56 46 93 39 49 69 61]
