In [17]:
import numpy as np

matrix = np.random.randint(0,100, size=(3,3))
print(f"Original matrix: \n{matrix}\n")
flat = matrix.flatten()
print(f"Converted 1D array: {flat}")

Original matrix: 
[[99 22 33]
 [88 30 52]
 [40 95 66]]

Converted 1D array: [99 22 33 88 30 52 40 95 66]


In [ ]:
print(flat[0:3]) # Print elements from index 0 to 2 (index 3 is excluded)

print(flat[:3]) # Print the first three elements (same as flat[0:3])

print(flat[3]) # Print the element at index 3

print(flat[3:7]) # Print elements from index 3 to 6 (index 7 is excluded)

print(flat[::2]) # Every 2nd element

print(flat[9:7]) # Print elements from index 9 to 6
# Since start index > end index, no elements are selected

[99 22 33]
[99 22 33]
88
[88 30 52 40]
[99 33 30 40 66]
[]


## 📌 NumPy Slicing: View vs Copy (Important Concept)

In NumPy, **slicing does NOT create a copy of the array**.  
Instead, it returns a **view** of the original array.

### What does this mean?
- A **view** shares the same memory as the original array
- Any modification in the sliced array **directly affects** the original array
- This design improves **performance** and **memory efficiency**

---

### Example: Slicing Creates a View
```python
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

slice_arr = arr[1:4]   # Slice from index 1 to 3
slice_arr[0] = 999     # Modify the slice

print(arr)


In [28]:
import numpy as np

arr = np.array([1,2,3,4,51,23,78,76,23,65,99])
print(f"Array: {arr}\n")

# Fancy indexing: selecting elements at indices 1, 4, and 6
print(arr[[1,4,6]])
print(arr>25)

Array: [ 1  2  3  4 51 23 78 76 23 65 99]

[ 2 51 78]
[False False False False  True False  True  True False  True  True]
