In [23]:
import numpy as np

arr = np.random.randint(10,50, size=(3,4))
print(arr)

[[38 31 48 25]
 [24 24 42 11]
 [10 44 40 49]]


In [27]:
colSum = np.sum(arr, axis=0) # column-wise operation
print(colSum)
rowSum = np.sum(arr, axis=1) # row-wise operation
print(rowSum)

[ 72  99 130  85]
[142 101 143]


In [28]:
val = arr[0,1] # Access the element at row index 0 and column index 1
print(val)

31


In [29]:
val = arr[0:1]
print(val)

[[38 31 48 25]]


In [ ]:
# Slice rows from index 0 to 1 and columns from index 1 to 2 (end index excluded)

val = arr[0:2,1:3]
print(val)

[[31 48]
 [24 42]]


In [ ]:
# Get all rows of the first column

first_col = arr[ : , 0]
print(first_col)

[38 24 10]


In [10]:
# Get the first row each "sheet" in a 3D array

first_row = arr[0, :]
print(first_row)

[44 36 29 39]
