In [5]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])
newArr = arr ** 2 # Vectorized operation
print(newArr)

[ 1  4  9 16 25 36 49]


In [4]:
newArr + 10

array([11, 14, 19, 26, 35, 46, 59])

In [ ]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([7,8,9])

newArr = arr1 + arr2 # Broad Casting
print(newArr)

[[ 8 10 12]
 [11 13 15]]


In [ ]:
data = np.random.randint(0, 100, size=(9,3))
mean = data.mean(axis=0)
std = data.std(axis=0)

normalized_data = (data - mean) / std # Formula: (value − mean) / standard deviation
print(normalized_data)

[[-0.34504133  0.44871795 -1.36163093]
 [-1.07964545  1.79487179 -1.06394643]
 [-1.01286325 -0.32051282 -0.56780561]
 [ 0.99060252  0.94871795 -0.36934928]
 [ 0.3227806  -0.85897436  0.57331828]
 [ 1.1909491   0.64102564 -0.81587602]
 [-0.34504133 -1.16666667  1.46637177]
 [ 1.55825116 -0.05128205  0.8213887 ]
 [-1.27999202 -1.43589744  1.31752952]]
