In [5]:
import numpy as np


arr = np.random.randint(0, 100, size=(9,3))
print(f"Original matrix: \n {arr}")

Original matrix: 
 [[93 30 30]
 [52 10 53]
 [ 5 76 21]
 [84 29 78]
 [18  0 90]
 [21 26 77]
 [60 34 22]
 [22 78 82]
 [45 26 74]]


In [10]:
mean = np.mean(arr)
print(mean)

45.77777777777778


In [12]:
min = np.min(arr)
print(min)

0


In [14]:
max = np.max(arr)
print(max)

93


In [16]:
std = np.std(arr)
print(std)

28.4687396244103


In [18]:
avg = np.median(arr)
print(avg)

34.0


In [21]:
sum = np.sum(arr)
product = np.prod(arr)
print(f"The sum of the matrix is: {sum}, and the product of the matrix is: {product}")

The sum of the matrix is: 1236, and the product of the matrix is: 0


In [22]:
percentile = np.percentile(arr, 60)
print(percentile)

52.6


In [24]:
unique = np.unique(arr)
print(unique)

[ 0  5 10 18 21 22 26 29 30 34 45 52 53 60 74 76 77 78 82 84 90 93]
